### ISSUE TITLE
Build failing on mac

### ISSUE THREAD

**Issue by nerding-it** [jayantsinha/docker-logging-plugin#1]
When I run a build getting below error in Docker version 18.09.2

Sending build context to Docker daemon  129.5kB
Step 1/3 : FROM scratch
 ---> 
Step 2/3 : ADD docker-logging-driver /
ADD failed: stat /var/lib/docker/tmp/docker-builder366291491/docker-logging-driver: no such file or directory

**Comment by jayantsinha** [comment]
I missed mentioning that it expects the executable to be in place for docker build to work.
The container is linux based so you can build the code for linux amd64 like this:
`env GOOS=linux GOARCH=amd64 go build .`

Once you have your executable, the docker build should work.

**Comment by nerding-it** [comment]
After following steps as per latest README, I am able to build the image
